---
- hosts: demo
  become: yes
  tasks:
   - name: firsttask
     command: echo first
     tags:
       - first
       - g1
   - name: 2nd task
     command: echo 2nd
     tags:
       - second
   - name: 3rd task
     command: echo 3rd
     tags:
       - third
       - g1
