---
- hosts: demo
  become: yes
  pre_tasks:
   - name: start
     raw: echo start  
  roles:
   - { role: test, when: ansible_os_family == "RedHat" }
   - { role: dev, when: ansible_os_family == "Debian" }
  post_task:
   - name: stop
     raw: echo stop
