---
- hosts: demo

  become: yes

  vars:

  - myname: rmurali

  tasks:

   - name: print

     command: echo {{myname}}
     register: output
  # - debug: var=output.stdout
   - debug: var=output
...
